name: 'My first github action'

on: [ 'push', 'pull_request' ]

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: output value 1
      id: first
      shell: bash
      run: |
        echo "Hello World"

    - name: output value 2
      if: github.event_name == 'pull_request'
      id: first
      shell: bash
      run: |
        echo "Hello World 2"

  second-job:
    name: 'second job'
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: output value
      id: second
      shell: bash
      run: |
        echo "Hello World second job"