name: 'My first github action'

on: push

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |
        echo "Hello world from step 1"
        echo "STEP_VALUES_1=='THIS IS SET BY STEP 1'" >> $GITHUB_ENV
    
    - name: Say Hello World 2
      shell: pwsh
      run: |
        echo "Hello World from step 2"
        echo "VALUE: $env:STEP_VALUES_1"
        echo "VALUE: ${{ env.STEP_VALUES_1 }}"

    - name: Say Hello World 3
      shell: bash
      run: |
        echo "Hello World from step 3"
        echo "VALUE: STEP_VALUES_1"
        echo "VALUE: ${{ env.STEP_VALUES_1 }}"